Fix CGLibProxySerializerTest to show how to use CGLibProxySerializer with kryo2.
This made a change in kryo necessary to be able to override class by
name resolution, see commit 323dc6f1 in kryo:
https://github.com/EsotericSoftware/kryo/commit/323dc6f1

Also upgraded cglib, because with 2.2 the test failed with a

    VerifyError: class net.sf.cglib.core.DebuggingClassWriter overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V

The test now uses Kryo directly + Objenesis StdInstantiatorStrategy
instead of KryoReflectionFactorySupport.